2023-10-18 02:38:58,735 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Configure stats pid to 3583892
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_023858-oywfsukp/logs/debug.log
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_023858-oywfsukp/logs/debug-internal.log
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_init.py:init():568] calling init triggers
2023-10-18 02:38:58,736 INFO    MainThread:3583892 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 02:38:58,737 INFO    MainThread:3583892 [wandb_init.py:init():593] re-initializing run, found existing run on stack: y25191s4
2023-10-18 02:38:58,738 INFO    MainThread:3583892 [wandb_run.py:_finish():1934] finishing run dwryu/TCN/y25191s4
2023-10-18 02:38:58,739 INFO    MainThread:3583892 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-18 02:38:58,739 INFO    MainThread:3583892 [wandb_run.py:_restore():2151] restore
2023-10-18 02:38:58,739 INFO    MainThread:3583892 [wandb_run.py:_restore():2157] restore done
2023-10-18 02:39:14,076 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3599] rendering history
2023-10-18 02:39:14,077 INFO    MainThread:3583892 [wandb_run.py:_footer_history_summary_info():3631] rendering summary
2023-10-18 02:39:14,088 INFO    MainThread:3583892 [wandb_run.py:_footer_sync_info():3558] logging synced files
2023-10-18 02:39:14,141 INFO    MainThread:3583892 [wandb_init.py:init():618] starting backend
2023-10-18 02:39:14,142 INFO    MainThread:3583892 [wandb_init.py:init():622] setting up manager
2023-10-18 02:39:14,145 INFO    MainThread:3583892 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-18 02:39:14,145 INFO    MainThread:3583892 [wandb_init.py:init():628] backend started and connected
2023-10-18 02:39:14,158 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-18 02:39:14,158 INFO    MainThread:3583892 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-18 02:39:14,158 INFO    MainThread:3583892 [wandb_init.py:init():720] updated telemetry
2023-10-18 02:39:14,160 INFO    MainThread:3583892 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-18 02:39:20,641 INFO    MainThread:3583892 [wandb_run.py:_on_init():2220] communicating current version
2023-10-18 02:39:25,644 INFO    MainThread:3583892 [wandb_run.py:_on_init():2229] got version response 
2023-10-18 02:39:25,644 INFO    MainThread:3583892 [wandb_init.py:init():804] starting run threads in backend
2023-10-18 02:39:29,334 INFO    MainThread:3583892 [wandb_run.py:_console_start():2199] atexit reg
2023-10-18 02:39:29,334 INFO    MainThread:3583892 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-18 02:39:29,334 INFO    MainThread:3583892 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-18 02:39:29,335 INFO    MainThread:3583892 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-18 02:39:29,335 INFO    MainThread:3583892 [wandb_init.py:init():845] run started, returning control to user process
2023-10-18 02:41:59,201 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 02:41:59,201 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Configure stats pid to 3583892
2023-10-18 02:41:59,201 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 02:41:59,201 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 02:41:59,201 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 02:41:59,201 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 02:41:59,201 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 02:41:59,202 INFO    MainThread:3583892 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_024159-my769vss/logs/debug.log
2023-10-18 02:41:59,202 INFO    MainThread:3583892 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_024159-my769vss/logs/debug-internal.log
2023-10-18 02:41:59,202 INFO    MainThread:3583892 [wandb_init.py:init():568] calling init triggers
2023-10-18 02:41:59,202 INFO    MainThread:3583892 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 02:41:59,202 INFO    MainThread:3583892 [wandb_init.py:init():593] re-initializing run, found existing run on stack: oywfsukp
2023-10-18 02:41:59,204 INFO    MainThread:3583892 [wandb_run.py:_finish():1934] finishing run dwryu/TCN/oywfsukp
2023-10-18 02:41:59,204 INFO    MainThread:3583892 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-18 02:41:59,204 INFO    MainThread:3583892 [wandb_run.py:_restore():2151] restore
2023-10-18 02:41:59,205 INFO    MainThread:3583892 [wandb_run.py:_restore():2157] restore done
2023-10-18 02:44:19,507 WARNING MsgRouterThr:3583892 [router.py:message_loop():77] message_loop has been closed
2023-10-18 02:44:25,246 INFO    MainThread:3583892 [wandb_run.py:_restore():2151] restore
2023-10-18 02:44:25,246 INFO    MainThread:3583892 [wandb_run.py:_restore():2157] restore done
2023-10-18 02:44:25,332 ERROR   MainThread:3583892 [wandb_init.py:init():1198] error
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2177, in _atexit_cleanup
    self._on_finish()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2416, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 298, in wait
    on_probe(probe_handle)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2381, in _on_probe_exit
    result = handle.wait(timeout=0)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 603, in init
    latest_run.finish()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 419, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 360, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1925, in finish
    return self._finish(exit_code, quiet)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1940, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2188, in _atexit_cleanup
    self._backend.cleanup()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/backend/backend.py", line 232, in cleanup
    self.interface.join()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 522, in join
    super().join()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 680, in join
    _ = self._communicate_shutdown()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 419, in _communicate_shutdown
    _ = self._communicate(record)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 291, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 60, in _communicate_async
    future = self._router.send_and_receive(rec, local=local)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 94, in send_and_receive
    self._send_message(rec)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 36, in _send_message
    self._sock_client.send_record_communicate(record)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 216, in send_record_communicate
    self.send_server_request(server_req)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-10-18 02:44:35,990 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 02:44:35,990 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Configure stats pid to 3583892
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_024435-ne4kh9d5/logs/debug.log
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_024435-ne4kh9d5/logs/debug-internal.log
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_init.py:init():568] calling init triggers
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_init.py:init():593] re-initializing run, found existing run on stack: oywfsukp
2023-10-18 02:44:35,993 INFO    MainThread:3583892 [wandb_run.py:_finish():1934] finishing run dwryu/TCN/oywfsukp
