2023-10-18 02:44:35,990 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 02:44:35,990 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Configure stats pid to 3583892
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_024435-ne4kh9d5/logs/debug.log
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_024435-ne4kh9d5/logs/debug-internal.log
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_init.py:init():568] calling init triggers
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 02:44:35,991 INFO    MainThread:3583892 [wandb_init.py:init():593] re-initializing run, found existing run on stack: oywfsukp
2023-10-18 02:44:35,993 INFO    MainThread:3583892 [wandb_run.py:_finish():1934] finishing run dwryu/TCN/oywfsukp
2023-10-18 02:44:36,044 ERROR   MainThread:3583892 [wandb_init.py:init():1198] error
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 603, in init
    latest_run.finish()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 419, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 360, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1925, in finish
    return self._finish(exit_code, quiet)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1953, in _finish
    manager._inform_finish(run_id=self._run_id)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 213, in _inform_finish
    svc_iface._svc_inform_finish(run_id=run_id)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 52, in _svc_inform_finish
    self._sock_client.send(inform_finish=inform_finish)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
